// <auto-generated />
namespace Wchl.WMBlog.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FeacherAddTopic1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FeacherAddTopic1));
        
        string IMigrationMetadata.Id
        {
            get { return "201806260723591_Feacher-Add-Topic1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
